_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_res2net_bifpn_backbone"
  BIFPN:
    NUM_BIFPN: 7
    OUT_CHANNELS: 288
  WEIGHTS: "/home/centernet2/output/inference_dense_test_2020/model_final.pth"
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  CENTERNET:
    PRE_NMS_TOPK_TRAIN: 4000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 4000
    POST_NMS_TOPK_TEST: 2000
    USE_DEFORMABLE: True
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
TEST:
  EVAL_PERIOD: 40
  DETECTIONS_PER_IMAGE: 1000
SOLVER:
  MAX_ITER: 1125
  CHECKPOINT_PERIOD: 40
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.00025
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  RESET_ITER: True
DATASETS:
  TRAIN: "('dense_train_2021',)"
  TEST: "('dense_test_99',)"
  TRAINPATH: "/home/centernet2/datasets/dense_train_2021.txt"
  TESTPATH: "/home/centernet2/datasets/dense_test_99.txt"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  TEST_SIZE: 640
  TEST_INPUT_TYPE: 'rectangle'

